CREATE TABLE IF NOT EXISTS "public"."bot_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "data" "jsonb",
    "lang" "text",
    "type" "text",
    "title" "text"
);

ALTER TABLE "public"."bot_logs" OWNER TO "postgres";

ALTER TABLE "public"."bot_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bot_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."bot_logs"
    ADD CONSTRAINT "bot_logs_pkey" PRIMARY KEY ("id");

GRANT ALL ON TABLE "public"."bot_logs" TO "anon";
GRANT ALL ON TABLE "public"."bot_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."bot_logs" TO "service_role";

GRANT ALL ON SEQUENCE "public"."bot_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bot_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bot_logs_id_seq" TO "service_role";
