CREATE TABLE IF NOT EXISTS "public"."games_chats" (
    "id" bigint NOT NULL,
    "chat_id" bigint,
    "user_id" bigint,
    "punctuation" numeric,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "character_id" bigint,
    "time" numeric,
    "lang" "text" DEFAULT 'cat'::"text" NOT NULL
);

ALTER TABLE "public"."games_chats" OWNER TO "postgres";

ALTER TABLE "public"."games_chats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."games_chats"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."games_chats"
    ADD CONSTRAINT "games_chats_character_id_fkey" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."games_chats"
    ADD CONSTRAINT "games_chats_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");

GRANT ALL ON TABLE "public"."games_chats" TO "anon";
GRANT ALL ON TABLE "public"."games_chats" TO "authenticated";
GRANT ALL ON TABLE "public"."games_chats" TO "service_role";

GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "service_role";
