CREATE TABLE IF NOT EXISTS "public"."front_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "error" "text",
    "type" "text",
    "details" "jsonb",
    "user_id" bigint
);

ALTER TABLE "public"."front_logs" OWNER TO "postgres";

ALTER TABLE "public"."front_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."front_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."front_logs"
    ADD CONSTRAINT "front_logs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."front_logs"
    ADD CONSTRAINT "front_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."front_logs" TO "anon";
GRANT ALL ON TABLE "public"."front_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."front_logs" TO "service_role";

GRANT ALL ON SEQUENCE "public"."front_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."front_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."front_logs_id_seq" TO "service_role";
