CREATE TABLE IF NOT EXISTS "public"."characters_chats" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "chat_id" bigint,
    "character_id" bigint NOT NULL
);

ALTER TABLE "public"."characters_chats" OWNER TO "postgres";

ALTER TABLE "public"."characters_chats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."characters_chats_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."characters_chats"
    ADD CONSTRAINT "characters_chats_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."characters_chats"
    ADD CONSTRAINT "characters_chats_character_id_fkey" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id");

GRANT ALL ON TABLE "public"."characters_chats" TO "anon";
GRANT ALL ON TABLE "public"."characters_chats" TO "authenticated";
GRANT ALL ON TABLE "public"."characters_chats" TO "service_role";

GRANT ALL ON SEQUENCE "public"."characters_chats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."characters_chats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."characters_chats_id_seq" TO "service_role";
